@startuml

    class SomethingsApiServiceImpl {
        +add(Something, SecurityContext): Response
        +findAll(SecurityContext): Response
        +findById(Long, SecurityContext): Response
        +remove(Something, SecurityContext): Response
        +update(Something, SecurityContext): Response
    }

@enduml
