@startuml

    class ApiResponseMessage {
        {static} +ERROR: int
        {static} +WARNING: int
        {static} +INFO: int
        {static} +OK: int
        {static} +TOO_BUSY: int
        +ApiResponseMessage()
        +ApiResponseMessage(int, String)
        +getCode(): int
        +setCode(int): void
        +getType(): String
        +setType(String): void
        +getMessage(): String
        +setMessage(String): void
    }

@enduml
