@startuml

    class OtherObject.OtherObjectBuilder {
        +id(Long): OtherObject.OtherObjectBuilder
        +name(String): OtherObject.OtherObjectBuilder
        +build(): OtherObject
    }

@enduml
