@startuml

    namespace de.tk.tkapp.rest.api.handler.factories {

        class SomethingsApiServiceFactory {
            {static} +getSomethingsApi(): SomethingsApiService
        }

    }

@enduml
